### PR TITLE
creating a pull request for improvements that Ralph has made to the pipeline example

### PR DESCRIPTION
**Pull request by steve-kansa**

### CODE REVIEW

**Comment by ralphnuessecpwr** [comment]
I added the code for an example of a pipeline from a shared library. The code is still as I use it in my own example. Some things we should change near term:
- Move user specific parameters from the pipeline call to configuration files: A customer pipeline will likely not use user specific credential tokens but using tokens setup specifically for the Jenkins server.
- Use the Config File Provider plugin for the remaining two config files: I used both methods (Config File plugin and "plain" file) two show both methods of using files.
- Change any references to Compuware specific assets to "placeholders", e.g. SonarQube server URL etc.

**Comment by steve-kansa** [comment]
@ralphnuessecpwr before we merge this I think we should make sure we have the directory structure defined.  I think we should put the jenkins pipeline examples all under jenkinsfiles but then maybe have subdirectories to separate some different types of pipelines?

**Comment by ralphnuessecpwr** [comment]
@steve-kansa If I understand the use of Shared Libraries correctly (https://jenkins.io/doc/book/pipeline/shared-libraries/) they require the folders 'vars' and 'src' to be present under the root of the repository. If we want the code we publish here to be usable directly from this repository (not sure if we want that, e.g. for future FTS demo pipelines), than we need to roughly have the folder structure I describe here (https://cpwr-devops.github.io/DevOps-Examples/index.html#The complete folder structure). I agree, though, that we should store anything that is "traditional" pipeline or Jenkins groovy code snippet in the jenkinsfiles folder. Should we create an "other source" folder for code like you powershell script?

**Comment by ralphnuessecpwr** [comment]
@steve-kansa It's been a while since I have published something. I have added two more examples to the "suggest" branch. 
One gets triggered when generating code in ISPW and executes unit tests against the tasks in the generate set.
The other gets triggered on promote and executes functional tests.
I am wondering, if we should start merging into the master branch, so that it's easier for people to find the sources? According to Git there will be no merging conflicts.

**Comment by steve-kansa** [comment]
@ralphnuessecpwr yes i would merge it into the master.

**Pull request merged**
